<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-T6D122N" ignored="0" name="book flight 1" tests="5" failures="1" timestamp="23 Oct 2022 18:31:55 GMT" time="42.198" errors="0">
  <testcase name="registrationPage" time="8.257" classname="com.newtours.tests.BookFlightTest"/>
  <testcase name="registrationConfirmationPage" time="0.22" classname="com.newtours.tests.BookFlightTest"/>
  <testcase name="flightDetailsPage" time="5.45" classname="com.newtours.tests.BookFlightTest"/>
  <testcase name="findFlightPage" time="0.428" classname="com.newtours.tests.BookFlightTest"/>
  <testcase name="flightConfPage" time="0.357" classname="com.newtours.tests.BookFlightTest">
    <failure type="java.lang.AssertionError" message="expected [$584 USD] but found [$585 USD]">
      <![CDATA[java.lang.AssertionError: expected [$584 USD] but found [$585 USD]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.newtours.tests.BookFlightTest.flightConfPage(BookFlightTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- flightConfPage -->
</testsuite> <!-- book flight 1 -->
